### ISSUE TITLE
Developer tab

### ISSUE THREAD

**Issue by jontey** [aleixmorgadas/nem2-wallet-browserextension#1]
This is by no means a definitive roadmap. I am only opening this issue to help keep track of functions that I think might be useful that I am working on.

### Use case
Primarily for quick reference. Instead of pulling up the typescript SDK and writing node.js there is a more cohesive way to check if values are correct, etc. Main example is with the new mosaic implementation, conversion to readable format for mosaicId are helpful to set up a custom chain.

### Functions
Account functions (I think most of this is inherently part of the "wallet" section. Anyways..)
- [x] Private key to public key to address
- [x] Address beautifier (remove or add '-' to address)
- [x] Address encoding/decoding (hex to string mainly)

Conversion functions
- [x] String to hex converter to unit64
- [x] Block timestamp converter

Namespace + mosaic
- [x] NamespaceId/MosaicId calculator

Good baseline https://nem2-dev-ui.netlify.com (without most of the endpoint features).

**Comment by aleixmorgadas** [comment]
Hi @jontey, thanks for sharing interest in the project!

I've not the main wallet structure, but I would suggest you start creating the component and adding it to [src/components/wallet.vue](https://github.com/aleixmorgadas/cw-extension/blob/master/src/components/wallet.vue).

So, you could create a Component and add it to the [Wallet Component](https://github.com/aleixmorgadas/cw-extension/blob/master/src/components/wallet.vue). It will appear in the main page and it's OK until I've the main structure (like Vue router, ...).

Feel free to make a Pull Request with this features ^^

**Comment by aleixmorgadas** [comment]
Hi @jontey, I created the [DeveloperMode component](https://github.com/aleixmorgadas/cw-extension/blob/master/src/components/DeveloperMode.vue) and added it into the Menu.

The structure that I've will stay for some time, feel free too add some features there ^^

![image](https://user-images.githubusercontent.com/5518197/54082278-08a54800-4313-11e9-995b-cd3cd8b22f32.png)

**Comment by aleixmorgadas** [comment]
@jontey , be careful about how the account is generated. Private and public nets use a different hash version to generate accounts and sign transactions.

- Private network: SHA3
- Public network: Keccak 

So, the development tab should take care of that situation. Indeed, the SDK should take care of that situation, meanwhile, I suggest you to remove TESTNET and MAIN_NET to not let into wrong scenarios

**Comment by jontey** [comment]
@aleixmorgadas If I understand correctly, you are referring to the different hashing functions used in catapult vs NIS1, not that private and public net (if both are running catapult) will use two different hashing functions?

**Comment by aleixmorgadas** [comment]
> If I understand correctly, you are referring to the different hashing functions used in catapult vs NIS1, not that private and public net (if both are running catapult) will use two different hashing functions?

AFAIK, public network on catapult will use the hash functions used on NIS1, but I guess @dgarcia360 or @Jaguar0625 can answer better the reason of that.

**Comment by jontey** [comment]
Closing issue. All baseline features are in.
