### ISSUE TITLE
Import account from private key

### ISSUE THREAD

**Issue by decentraliser** [aleixmorgadas/nem2-wallet-browserextension#29]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't import an account from a private key

**Describe the solution you'd like**
Add that function in the wallet tab

**Comment by aleixmorgadas** [comment]
Looks good! please, if you find something that can be improved, just PR. I don't aim to be the "feature approval", if it's common sense, I more than happy to merge the pull request ^^
