### ISSUE TITLE
Account information

### ISSUE THREAD

**Issue by aleixmorgadas** [aleixmorgadas/nem2-wallet-browserextension#6]
The user should view the account information:

- [x] Address, Public Key, Private Key
- [x] Owned assets
- [x] Rented namespaces
- [x] Transaction history (full)
  - [x] With transaction details

**Comment by decentraliser** [comment]
I can do a PR in the next 48h

**Comment by aleixmorgadas** [comment]
Cool! please do not hesitate to share your thoughts and ways to make this batter keeping the simplicity.

glad to see you helping in this project!

**Comment by decentraliser** [comment]
this looks good to me, only the modigy account types miss in the tx explorer but not needed now imo
