### ISSUE TITLE
Add transaction filter

### ISSUE THREAD

**Issue by NemTechCN** [aleixmorgadas/nem2-wallet-browserextension#60]
I added a panel to modify filter.

On the one hand, the PropertyType is divided into two parts, allow and block. On the other hand ,it is also divided into parts address, mosaic, transaction.

The new code Implement three kind of filters.

![image](https://user-images.githubusercontent.com/45383558/56495449-5b843900-6528-11e9-892e-a0bf96321161.png)

**Comment by aleixmorgadas** [comment]
Thanks for contributing!

**Comment by aleixmorgadas** [comment]
#61 merged
